### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by ChayimFriedman2** [Gankra/sptr#1]
https://github.com/Gankra/sptr/blob/d23e83391b7071e8f2ac643ab12556e5f8a07c80/src/func.rs#L3-L7

I suppose that is a typo?

**Comment by Gankra** [comment]
Whoops, must have accidentally deleted that :x

**Comment by Gankra** [comment]
Fixed on main, will hopefully cut 0.3.0 in the next day or two (waiting for some upstream stuff to land).
