### ISSUE TITLE
`expose_addr` is marked as `#[must_use]`

### ISSUE THREAD

**Issue by Imberflur** [Gankra/sptr#7]
I noticed that `expose_addr` is marked as `#[must_use]` even though in some cases the returned value won't be used.

My use case involves using `mmap` to get a large chunk of memory with a specific alignment so that any references to values placed in that memory can be used to compute the start address of that memory (where some metadata is located and from which relative offsets can be added).

So in this case, `expose_addr` is used once after getting the memory from `mmap` and later the address to provide to `from_exposed_addr` is independently computed.

**Comment by Gankra** [comment]
I think you probably want to be explicit about that kind of thing -- rust has idioms for explicitly discarding results you "should use":

```
let _ = ptr.expose_addr()
```

Although I'm a little confused by how what you're describing could possibly work? Do you have a hardcoded address you're asking memmap for, so you don't need to remember what memmap returns..?

**Comment by Imberflur** [comment]
The requested addresses are always aligned to a large hardcoded alignment (e.g. 1 GB) and the memory used is less than that, so any address in this memory can be used to determine the start address by masking out the lower bits.

**Comment by Imberflur** [comment]
I'm happy to discard the value explicitly :slightly_smiling_face: , I was just initially a bit surprised that this is marked with `must_use` since a significant portion of its effect doesn't necessarily involve using the returned value. So I thought this might be something to consider. But I'm not very familiar with the general rules used to determine when to use `must_use` nor the other uses cases for this method where this warning would be helpful.

**Comment by Gankra** [comment]
must_use is basically "it's probably a bug for you to call this and not use the result", which I think holds true for expose_addr, but certainly if you're doing something clever enough then you're always within your rights to discard it.
